
import { Product, Customer, Supplier, User } from './types';

export const CURRENCY = 'TND';
export const TVA_RATES = [7, 13, 19];

export const CATEGORIES = [
  { id: 'Épicerie', label: 'Épicerie Sèche', icon: '🍝', color: 'bg-orange-100 text-orange-700 border-orange-200', img: 'https://images.unsplash.com/photo-1551462147-37885acc3c41?w=400&h=400&fit=crop' },
  { id: 'Frais', label: 'Frais & Crémerie', icon: '🥛', color: 'bg-emerald-100 text-emerald-700 border-emerald-200', img: 'https://images.unsplash.com/photo-1550583724-125581fe2f83?w=400&h=400&fit=crop' },
  { id: 'Boissons', label: 'Eaux & Boissons', icon: '🥤', color: 'bg-blue-100 text-blue-700 border-blue-200', img: 'https://cdn.geantdrive.tn/tunis-city/1267797-home_default/eau-minerale.jpg' },
  { id: 'Biscuits', label: 'Sucreries & Biscuits', icon: '🍪', color: 'bg-amber-100 text-amber-700 border-amber-200', img: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop' },
  { id: 'Entretien', label: 'Entretien Maison', icon: '✨', color: 'bg-slate-100 text-slate-700 border-slate-200', img: 'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400&h=400&fit=crop' },
  { id: 'Hygiène', label: 'Hygiène & Beauté', icon: '🧼', color: 'bg-purple-100 text-purple-700 border-purple-200', img: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=400&fit=crop' },
  { id: 'Bébé', label: 'Univers Bébé', icon: '👶', color: 'bg-sky-100 text-sky-700 border-sky-200', img: 'https://cdn.geantdrive.tn/tunis-city/1194576-home_default/lingettes-bebe.jpg' },
  { id: 'Maison', label: 'Maison & Déco', icon: '🏠', color: 'bg-rose-100 text-rose-700 border-rose-200', img: 'https://cdn.geantdrive.tn/tunis-city/1152703-home_default/entonnoir.jpg' }
];

const RAW_DATA = [
  // ==================== BOISSONS (51 produits) ====================
  { n: 'Eau minérale', p: 0.300, i: 'https://cdn.geantdrive.tn/tunis-city/1306843-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Boisson instantannée Fraise', p: 0.320, i: 'https://cdn.geantdrive.tn/tunis-city/1304647-home_default/boisson-instantannee.jpg', c: 'Boissons' },
  { n: 'Boisson instantannée Citron', p: 0.320, i: 'https://cdn.geantdrive.tn/tunis-city/1304649-home_default/boisson-instantannee.jpg', c: 'Boissons' },
  { n: 'Boisson instantannée Menthe', p: 0.320, i: 'https://cdn.geantdrive.tn/tunis-city/1304648-home_default/boisson-instantannee.jpg', c: 'Boissons' },
  { n: 'Boisson instantannée Orange', p: 0.320, i: 'https://cdn.geantdrive.tn/tunis-city/1304646-home_default/boisson-instantannee.jpg', c: 'Boissons' },
  { n: 'Boisson instantannée Multifruits', p: 0.320, i: 'https://cdn.geantdrive.tn/tunis-city/1327751-home_default/boisson-instantannee.jpg', c: 'Boissons' },
  { n: 'Eau minérale Safia 1L', p: 0.400, i: 'https://cdn.geantdrive.tn/tunis-city/1267797-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau plate 0.5L', p: 0.400, i: 'https://cdn.geantdrive.tn/tunis-city/1144012-home_default/eau-plate.jpg', c: 'Boissons' },
  { n: 'Eau minérale Sabrine 0.5L', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1310504-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Sabrine 1L', p: 0.420, i: 'https://cdn.geantdrive.tn/tunis-city/1184289-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Ain Garci 1L', p: 0.420, i: 'https://cdn.geantdrive.tn/tunis-city/1253849-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Safia 1.5L', p: 0.420, i: 'https://cdn.geantdrive.tn/tunis-city/1327426-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Ain Garci 1.5L', p: 0.450, i: 'https://cdn.geantdrive.tn/tunis-city/1339977-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau gazéifiée Garci 1L', p: 0.450, i: 'https://cdn.geantdrive.tn/tunis-city/1219791-home_default/eau-gazeifiee.jpg', c: 'Boissons' },
  { n: 'Eau de source 1L', p: 0.450, i: 'https://cdn.geantdrive.tn/tunis-city/1327370-home_default/eau-de-source.jpg', c: 'Boissons' },
  { n: 'Eau gazéifiée Garci 1.5L', p: 0.480, i: 'https://cdn.geantdrive.tn/tunis-city/1219796-home_default/eau-gazeifiee.jpg', c: 'Boissons' },
  { n: 'Eau minérale Ain Garci 2L', p: 0.500, i: 'https://cdn.geantdrive.tn/tunis-city/1180863-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Safia 2L', p: 0.510, i: 'https://cdn.geantdrive.tn/tunis-city/1325815-home_default/eau-de-source.jpg', c: 'Boissons' },
  { n: 'Eau minérale Sabrine 2L', p: 0.560, i: 'https://cdn.geantdrive.tn/tunis-city/1190212-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Boisson au jus Orange 1L', p: 0.570, i: 'https://cdn.geantdrive.tn/tunis-city/1270717-home_default/boisson-au-jus.jpg', c: 'Boissons' },
  { n: 'Eau de source Sabrine 1.5L', p: 0.610, i: 'https://cdn.geantdrive.tn/tunis-city/1186685-home_default/eau-de-source.jpg', c: 'Boissons' },
  { n: 'Eau gazéifiée Safia 1.5L', p: 0.620, i: 'https://cdn.geantdrive.tn/tunis-city/1267719-home_default/eau-gazeifiee.jpg', c: 'Boissons' },
  { n: 'Boisson au jus Pêche 1L', p: 0.620, i: 'https://cdn.geantdrive.tn/tunis-city/1342482-home_default/boisson-au-jus.jpg', c: 'Boissons' },
  { n: 'Eau minérale Ain Garci 5L', p: 0.630, i: 'https://cdn.geantdrive.tn/tunis-city/1153933-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Sabrine 5L', p: 0.640, i: 'https://cdn.geantdrive.tn/tunis-city/1184578-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Safia 5L', p: 0.650, i: 'https://cdn.geantdrive.tn/tunis-city/1221446-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau de source 5L', p: 0.650, i: 'https://cdn.geantdrive.tn/tunis-city/1351166-home_default/eau-de-source.jpg', c: 'Boissons' },
  { n: 'Eau minérale Ain Garci 6L', p: 0.660, i: 'https://cdn.geantdrive.tn/tunis-city/1338997-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau gazéifiée Garci 6L', p: 0.670, i: 'https://cdn.geantdrive.tn/tunis-city/1226504-home_default/eau-gazeifiee.jpg', c: 'Boissons' },
  { n: 'Eau de source Safia 6L', p: 0.670, i: 'https://cdn.geantdrive.tn/tunis-city/1327369-home_default/eau-de-source.jpg', c: 'Boissons' },
  { n: 'Eau minérale Safia 6L', p: 0.690, i: 'https://cdn.geantdrive.tn/tunis-city/1142617-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Sabrine 6L', p: 0.690, i: 'https://cdn.geantdrive.tn/tunis-city/1339978-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Ain Garci 8L', p: 0.700, i: 'https://cdn.geantdrive.tn/tunis-city/1226500-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Sabrine 8L', p: 0.720, i: 'https://cdn.geantdrive.tn/tunis-city/1310505-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Safia 8L', p: 0.720, i: 'https://cdn.geantdrive.tn/tunis-city/1338998-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Eau minérale Ain Garci 10L', p: 0.750, i: 'https://cdn.geantdrive.tn/tunis-city/1180866-home_default/eau-minerale.jpg', c: 'Boissons' },
  { n: 'Boisson au jus Multifruits 1L', p: 0.750, i: 'https://cdn.geantdrive.tn/tunis-city/1328621-home_default/boisson-au-jus.jpg', c: 'Boissons' },
  { n: 'Boisson au jus Ananas 1L', p: 0.750, i: 'https://cdn.geantdrive.tn/tunis-city/1328620-home_default/boisson-au-jus.jpg', c: 'Boissons' },

  // ==================== EPICERIE (45 produits) ====================
  { n: 'Pâtes chorba Randa', p: 0.225, i: 'https://cdn.geantdrive.tn/tunis-city/1267774-home_default/pates-chorba.jpg', c: 'Épicerie' },
  { n: 'Pâte chorba Millet Diari', p: 0.225, i: 'https://cdn.geantdrive.tn/tunis-city/1267773-home_default/pate-chorba-millet.jpg', c: 'Épicerie' },
  { n: 'Pâte millet Diari', p: 0.225, i: 'https://cdn.geantdrive.tn/tunis-city/1219668-home_default/pate-millet.jpg', c: 'Épicerie' },
  { n: 'Gâteau Madeleine', p: 0.270, i: 'https://cdn.geantdrive.tn/tunis-city/1255444-home_default/gateau.jpg', c: 'Biscuits' },
  { n: 'Gâteau Cake aux fruits', p: 0.270, i: 'https://cdn.geantdrive.tn/tunis-city/1255446-home_default/gateau.jpg', c: 'Biscuits' },
  { n: 'Chocolat Maestro Noir', p: 0.290, i: 'https://cdn.geantdrive.tn/tunis-city/1223067-home_default/chocolat.jpg', c: 'Biscuits' },
  { n: 'Gaufrettes Kif Chocolat', p: 0.300, i: 'https://cdn.geantdrive.tn/tunis-city/1158564-home_default/gaufrettes.jpg', c: 'Biscuits' },
  { n: 'Gaufrette ChocoLait', p: 0.300, i: 'https://cdn.geantdrive.tn/tunis-city/1223053-home_default/gaufrette.jpg', c: 'Biscuits' },
  { n: 'Bonbon gélifié Haribo Fraise', p: 0.300, i: 'https://cdn.geantdrive.tn/tunis-city/1159790-home_default/bonbon-gelifie.jpg', c: 'Biscuits' },
  { n: 'Gaufrette Vanille', p: 0.300, i: 'https://cdn.geantdrive.tn/tunis-city/1223049-home_default/gaufrette.jpg', c: 'Biscuits' },
  { n: 'Chocolat fourré Noisette', p: 0.310, i: 'https://cdn.geantdrive.tn/tunis-city/1141774-home_default/chocolat-fourre.jpg', c: 'Biscuits' },
  { n: 'Chocolat fourré Lait', p: 0.310, i: 'https://cdn.geantdrive.tn/tunis-city/1223055-home_default/chocolat-fourre.jpg', c: 'Biscuits' },
  { n: 'Chocolat fourré Amande', p: 0.310, i: 'https://cdn.geantdrive.tn/tunis-city/1223059-home_default/chocolat-fourre.jpg', c: 'Biscuits' },
  { n: 'Bonbon gélifié Haribo Cola', p: 0.340, i: 'https://cdn.geantdrive.tn/tunis-city/1153325-home_default/bonbon-gelifie.jpg', c: 'Biscuits' },
  { n: 'Bonbon gélifié Haribo Citron', p: 0.340, i: 'https://cdn.geantdrive.tn/tunis-city/1153327-home_default/bonbon-gelifie.jpg', c: 'Biscuits' },
  { n: 'Barre biscuitée Chocolat', p: 0.390, i: 'https://cdn.geantdrive.tn/tunis-city/1306697-home_default/barre-biscuitee.jpg', c: 'Biscuits' },
  { n: 'Bonbon gélifié Dragibus', p: 0.390, i: 'https://cdn.geantdrive.tn/tunis-city/1223031-home_default/bonbon-gelifie.jpg', c: 'Biscuits' },
  { n: 'Poudre instantanée chocolat', p: 0.390, i: 'https://cdn.geantdrive.tn/tunis-city/1152904-home_default/poudre-instantanee-chocolat.jpg', c: 'Épicerie' },
  { n: 'Bonbon gélifié Chamallow', p: 0.390, i: 'https://cdn.geantdrive.tn/tunis-city/1223037-home_default/bonbon-gelifie.jpg', c: 'Biscuits' },
  { n: 'Bonbon assortiment', p: 0.400, i: 'https://cdn.geantdrive.tn/tunis-city/1310516-home_default/bonbon.jpg', c: 'Biscuits' },
  { n: 'Couscous moyen Diari 1kg', p: 0.400, i: 'https://cdn.geantdrive.tn/tunis-city/1257006-home_default/couscous-moyen.jpg', c: 'Épicerie' },
  { n: 'Pâte escargots', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219814-home_default/pate-escargots.jpg', c: 'Épicerie' },
  { n: 'Pâte fell', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1224753-home_default/pate-fell.jpg', c: 'Épicerie' },
  { n: 'Pâte coude', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1225028-home_default/pate-coude.jpg', c: 'Épicerie' },
  { n: 'Pâte fell rigati', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219843-home_default/pate-fell-rigati.jpg', c: 'Épicerie' },
  { n: 'Pâte twist', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1220855-home_default/pate-twist.jpg', c: 'Épicerie' },
  { n: 'Pâte ressort', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219838-home_default/pate-ressort.jpg', c: 'Épicerie' },
  { n: 'Pâte flamengo', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219840-home_default/pate-flamengo.jpg', c: 'Épicerie' },
  { n: 'Pâtes coude', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1223082-home_default/pates-coude.jpg', c: 'Épicerie' },
  { n: 'Pâte escargot', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219898-home_default/pate-escargot.jpg', c: 'Épicerie' },
  { n: 'Pâte plomb fin', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1221109-home_default/pate-plomb-fin.jpg', c: 'Épicerie' },
  { n: 'Pâte Mini Fusilli', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1205758-home_default/pate-mini-fusilli.jpg', c: 'Épicerie' },
  { n: 'Pâte Mini Penne', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1205761-home_default/pate-mini-penne.jpg', c: 'Épicerie' },
  { n: 'Pâte spaghetti N°2', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1226683-home_default/pate-spaghetti.jpg', c: 'Épicerie' },
  { n: 'Pâte cavatoni', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219879-home_default/pate-cavatoni.jpg', c: 'Épicerie' },
  { n: 'Pâte coquillettes', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219820-home_default/pate-coquillettes.jpg', c: 'Épicerie' },
  { n: 'Pâte fell rigate', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1225010-home_default/pate-fell.jpg', c: 'Épicerie' },
  { n: 'Pâte langue d\'oiseau', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1310526-home_default/pate-langue-d-oiseau.jpg', c: 'Épicerie' },
  { n: 'Pâte nouille Rose Blanche', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1301686-home_default/pate-nouille.jpg', c: 'Épicerie' },
  { n: 'Chorba millet Diari', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1344789-home_default/chorba-millet.jpg', c: 'Épicerie' },
  { n: 'Pâte spaghetti super', p: 0.410, i: 'https://cdn.geantdrive.tn/tunis-city/1219846-home_default/pate-spaghetti-super.jpg', c: 'Épicerie' },

  // ==================== CREMERIE & SURGELÉ (31 produits) ====================
  { n: 'Yaourt brassé Vitalait Nature', p: 0.430, i: 'https://cdn.geantdrive.tn/tunis-city/1297746-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Yaourt brassé Délice Nature', p: 0.430, i: 'https://cdn.geantdrive.tn/tunis-city/1282859-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Yaourt brassé Vitalait Bio', p: 0.430, i: 'https://cdn.geantdrive.tn/tunis-city/1325762-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Spécialité laitière brassée', p: 0.430, i: 'https://cdn.geantdrive.tn/tunis-city/1156839-home_default/specialite-laitiere-brassee.jpg', c: 'Frais' },
  { n: 'Yaourt brassé Danone Nature', p: 0.430, i: 'https://cdn.geantdrive.tn/tunis-city/1282869-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Yaourt brassé Jebali Nature', p: 0.430, i: 'https://cdn.geantdrive.tn/tunis-city/1198018-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Yaourt aromatisé Fraise', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1197825-home_default/yaourt-aromatise.jpg', c: 'Frais' },
  { n: 'Yaourt Nature', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1300188-home_default/yaourt.jpg', c: 'Frais' },
  { n: 'Yaourt aromatisé Vanille', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1325367-home_default/yaourt-aromatise.jpg', c: 'Frais' },
  { n: 'Yaourt aromatisé Abricot', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1325368-home_default/yaourt-aromatise.jpg', c: 'Frais' },
  { n: 'Yaourt aromatisé Citron', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1300197-home_default/yaourt-aromatise.jpg', c: 'Frais' },
  { n: 'Yaourt aromatisé Pêche', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1197828-home_default/yaourt-aromatise.jpg', c: 'Frais' },
  { n: 'Yaourt aromatisé Cerise', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1282852-home_default/yaourt-aromatise.jpg', c: 'Frais' },
  { n: 'Yaourt aromatisé Mangue', p: 0.540, i: 'https://cdn.geantdrive.tn/tunis-city/1325788-home_default/yaourt-aromatise.jpg', c: 'Frais' },
  { n: 'Yaourt brassé à la grecque', p: 0.600, i: 'https://cdn.geantdrive.tn/tunis-city/1325378-home_default/specialite-laitiere-brassee.jpg', c: 'Frais' },
  { n: 'Yaourt brassé Cerise', p: 0.620, i: 'https://cdn.geantdrive.tn/tunis-city/1282882-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Yaourt brassé Fraise', p: 0.620, i: 'https://cdn.geantdrive.tn/tunis-city/1270146-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Yaourt brassé Vanille', p: 0.620, i: 'https://cdn.geantdrive.tn/tunis-city/1270147-home_default/yaourt-brasse.jpg', c: 'Frais' },
  { n: 'Yaourt aux fruits Mix', p: 0.720, i: 'https://cdn.geantdrive.tn/tunis-city/1282880-home_default/yaourt-aux-fruits.jpg', c: 'Frais' },
  { n: 'Yaourt allégé Nature', p: 0.730, i: 'https://cdn.geantdrive.tn/tunis-city/1300183-home_default/yaourt.jpg', c: 'Frais' },
  { n: 'Yaourt à boire Fraise', p: 0.740, i: 'https://cdn.geantdrive.tn/tunis-city/1207954-home_default/yaourt-a-boire.jpg', c: 'Frais' },
  { n: 'Yaourt à boire Vanille', p: 0.740, i: 'https://cdn.geantdrive.tn/tunis-city/1208003-home_default/yaourt-a-boire.jpg', c: 'Frais' },
  { n: 'Crème dessert Chocolat', p: 0.780, i: 'https://cdn.geantdrive.tn/tunis-city/1157508-home_default/creme-dessert.jpg', c: 'Frais' },
  { n: 'Crème dessert Vanille', p: 0.780, i: 'https://cdn.geantdrive.tn/tunis-city/1191182-home_default/creme-dessert.jpg', c: 'Frais' },
  { n: 'Crème dessert Caramel', p: 0.780, i: 'https://cdn.geantdrive.tn/tunis-city/1278149-home_default/creme-dessert.jpg', c: 'Frais' },
  { n: 'Crème dessert Café', p: 0.780, i: 'https://cdn.geantdrive.tn/tunis-city/1278144-home_default/creme-dessert.jpg', c: 'Frais' },
  { n: 'Yaourt à boire Chocolat', p: 0.780, i: 'https://cdn.geantdrive.tn/tunis-city/1282864-home_default/yaourt-a-boire.jpg', c: 'Frais' },

  // ==================== LE MARCHÉ (39 produits) ====================
  { n: 'Baguette à la farine spéciale', p: 0.360, i: 'https://cdn.geantdrive.tn/tunis-city/1198631-home_default/baguette-a-la-farine-speciale.jpg', c: 'Épicerie' },
  { n: 'Celeri vert botte', p: 0.460, i: 'https://cdn.geantdrive.tn/tunis-city/1234239-home_default/celeri-vert.jpg', c: 'Épicerie' },
  { n: 'Blette botte', p: 0.460, i: 'https://cdn.geantdrive.tn/tunis-city/1332989-home_default/blette.jpg', c: 'Épicerie' },
  { n: 'Persil botte', p: 0.520, i: 'https://cdn.geantdrive.tn/tunis-city/1234422-home_default/persil.jpg', c: 'Épicerie' },
  { n: 'Pain sans sel', p: 0.600, i: 'https://cdn.geantdrive.tn/tunis-city/1204528-home_default/pain-sans-sel.jpg', c: 'Épicerie' },
  { n: 'Aneth botte', p: 0.690, i: 'https://cdn.geantdrive.tn/tunis-city/1260787-home_default/aneth.jpg', c: 'Épicerie' },
  { n: 'Coriandre botte', p: 0.690, i: 'https://cdn.geantdrive.tn/tunis-city/1259323-home_default/coriandre.jpg', c: 'Épicerie' },
  { n: 'Baguette traditionnelle française', p: 0.750, i: 'https://cdn.geantdrive.tn/tunis-city/1186153-home_default/baguette-traditionnelle-francaise.jpg', c: 'Épicerie' },
  { n: 'Kiwi pièce', p: 0.790, i: 'https://cdn.geantdrive.tn/tunis-city/1234172-home_default/kiwi.jpg', c: 'Épicerie' },
  { n: 'Pain céréales à l\'ancienne', p: 0.800, i: 'https://cdn.geantdrive.tn/tunis-city/1186494-home_default/pain-cereales-a-l-ancienne.jpg', c: 'Épicerie' },
  { n: 'Pâte à pizza', p: 0.850, i: 'https://cdn.geantdrive.tn/tunis-city/1316665-home_default/pate-a-pizza.jpg', c: 'Épicerie' },
  { n: 'Chou rouge pièce', p: 0.920, i: 'https://cdn.geantdrive.tn/tunis-city/1234489-home_default/chou-rouge.jpg', c: 'Épicerie' },
  { n: 'Chou vert pièce', p: 0.920, i: 'https://cdn.geantdrive.tn/tunis-city/1234485-home_default/chou-vert.jpg', c: 'Épicerie' },
  { n: 'Epi de pain', p: 0.950, i: 'https://cdn.geantdrive.tn/tunis-city/1186165-home_default/epi.jpg', c: 'Épicerie' },
  { n: 'Mini salami régaline', p: 0.960, i: 'https://cdn.geantdrive.tn/tunis-city/1239772-home_default/mini-salami-regaline.jpg', c: 'Frais' },
  { n: 'Pamplemousse rose A', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1269177-home_default/pamplemousse-rose-a.jpg', c: 'Épicerie' },
  { n: 'Pain en boule', p: 1.000, i: 'https://cdn.geantdrive.tn/tunis-city/1220511-home_default/pain-en-boule.jpg', c: 'Épicerie' },
  { n: 'Pain burger x4', p: 1.050, i: 'https://cdn.geantdrive.tn/tunis-city/847328-home_default/pain-burger.jpg', c: 'Épicerie' },
  { n: 'Malsouka semoule', p: 1.050, i: 'https://cdn.geantdrive.tn/tunis-city/1239758-home_default/malsouka-semoule.jpg', c: 'Épicerie' },
  { n: 'Malsouka plate', p: 1.070, i: 'https://cdn.geantdrive.tn/tunis-city/1239841-home_default/malsouka-plate.jpg', c: 'Épicerie' },
  { n: 'Mini salami dindino', p: 1.100, i: 'https://cdn.geantdrive.tn/tunis-city/1239785-home_default/mini-salami-dindino.jpg', c: 'Frais' },
  { n: 'Tabouna pain complet', p: 1.150, i: 'https://cdn.geantdrive.tn/tunis-city/1186232-home_default/tabouna-pain-complet.jpg', c: 'Épicerie' },
  { n: 'Fenouil avec fanes', p: 1.150, i: 'https://cdn.geantdrive.tn/tunis-city/1234700-home_default/fenouil-avec-fanes.jpg', c: 'Épicerie' },
  { n: 'Mini régaline de dinde', p: 1.190, i: 'https://cdn.geantdrive.tn/tunis-city/1237652-home_default/mini-regaline-de-dinde.jpg', c: 'Frais' },
  { n: 'Salami dicky dicky', p: 1.210, i: 'https://cdn.geantdrive.tn/tunis-city/1151468-home_default/salami-dicky-dicky.jpg', c: 'Frais' },
  { n: 'Salade romaine', p: 1.260, i: 'https://cdn.geantdrive.tn/tunis-city/1234108-home_default/salade-romaine.jpg', c: 'Épicerie' },
  { n: 'Radis local botte', p: 1.260, i: 'https://cdn.geantdrive.tn/tunis-city/1234302-home_default/radis-local.jpg', c: 'Épicerie' },
  { n: 'Baguette viennoise', p: 1.350, i: 'https://cdn.geantdrive.tn/tunis-city/1186237-home_default/baguette-viennoise.jpg', c: 'Épicerie' },
  { n: 'Chausson aux pommes', p: 1.350, i: 'https://cdn.geantdrive.tn/tunis-city/1186288-home_default/chausson-aux-pommes.jpg', c: 'Épicerie' },
  { n: 'Tomate allongée kg', p: 1.490, i: 'https://cdn.geantdrive.tn/tunis-city/1235766-home_default/tomate-allongee.jpg', c: 'Épicerie' },
  { n: 'Pain libanais (Raghif)', p: 1.490, i: 'https://cdn.geantdrive.tn/tunis-city/1186707-home_default/pain-libanais-15cm.jpg', c: 'Épicerie' },

  // ==================== HYGIÈNE & BEAUTÉ (43 produits) ====================
  { n: 'Masque barrière lavable', p: 0.900, i: 'https://cdn.geantdrive.tn/tunis-city/1155337-home_default/masque-barriere-lavable.jpg', c: 'Hygiène' },
  { n: 'Lingettes de voyage', p: 0.930, i: 'https://cdn.geantdrive.tn/tunis-city/1331782-home_default/lingettes-de-voyage.jpg', c: 'Hygiène' },
  { n: 'Savon de toilette Palm Olive', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1301809-home_default/savon-de-toilette.jpg', c: 'Hygiène' },
  { n: 'Savon de toilette Aloe Vera', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1331821-home_default/savon-de-toilette.jpg', c: 'Hygiène' },
  { n: 'Savon de toilette Miel', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1301810-home_default/savon-de-toilette.jpg', c: 'Hygiène' },
  { n: 'Savon de toilette Argan', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1315253-home_default/savon-de-toilette.jpg', c: 'Hygiène' },
  { n: 'Savon de toilette Lavande', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1301829-home_default/savon-de-toilette.jpg', c: 'Hygiène' },
  { n: 'Elastique chanielle', p: 1.050, i: 'https://cdn.geantdrive.tn/tunis-city/1265568-home_default/elastique-chanielle.jpg', c: 'Hygiène' },
  { n: 'Lingettes démaquillantes', p: 1.090, i: 'https://cdn.geantdrive.tn/tunis-city/1247507-home_default/lingettes.jpg', c: 'Hygiène' },
  { n: 'Crème oxydante 20vol', p: 1.190, i: 'https://cdn.geantdrive.tn/tunis-city/1247393-home_default/creme-oxydante.jpg', c: 'Hygiène' },
  { n: 'Oxydant 30vol', p: 1.190, i: 'https://cdn.geantdrive.tn/tunis-city/1302802-home_default/oxydant.jpg', c: 'Hygiène' },
  { n: 'Oxydant 40vol', p: 1.190, i: 'https://cdn.geantdrive.tn/tunis-city/1302988-home_default/oxydant.jpg', c: 'Hygiène' },
  { n: 'Crème oxydant 10vol', p: 1.390, i: 'https://cdn.geantdrive.tn/tunis-city/1302975-home_default/creme-oxydant.jpg', c: 'Hygiène' },
  { n: 'Serre tête pour bébé', p: 1.440, i: 'https://cdn.geantdrive.tn/tunis-city/1247432-home_default/serre-tete-pour-bebe.jpg', c: 'Hygiène' },
  { n: 'Brosse à teinture', p: 1.450, i: 'https://cdn.geantdrive.tn/tunis-city/1292324-home_default/brosse-a-teinture.jpg', c: 'Hygiène' },
  { n: 'Lingettes nettoyantes', p: 1.490, i: 'https://cdn.geantdrive.tn/tunis-city/1197744-home_default/lingettes.jpg', c: 'Hygiène' },
  { n: 'Savon de toilette Signal', p: 1.550, i: 'https://cdn.geantdrive.tn/tunis-city/1201552-home_default/savon-de-toilette.jpg', c: 'Hygiène' },
  { n: 'Brosse à dents Signal Medium', p: 1.550, i: 'https://cdn.geantdrive.tn/tunis-city/1182739-home_default/brosse-a-dents.jpg', c: 'Hygiène' },
  { n: 'Brosse à dents Signal Soft', p: 1.550, i: 'https://cdn.geantdrive.tn/tunis-city/1182737-home_default/brosse-a-dents.jpg', c: 'Hygiène' },
  { n: 'Brosse à dent Colgate', p: 1.550, i: 'https://cdn.geantdrive.tn/tunis-city/1182735-home_default/brosse-a-dent.jpg', c: 'Hygiène' },
  { n: 'Lingettes antibactériennes enfant', p: 1.590, i: 'https://cdn.geantdrive.tn/tunis-city/1350230-home_default/lingettes-antibacteriennes-pour-enfant.jpg', c: 'Hygiène' },
  { n: 'Brosse à dents pour enfant', p: 1.690, i: 'https://cdn.geantdrive.tn/tunis-city/1247426-home_default/brosse-a-dents-enfant.jpg', c: 'Hygiène' },
  { n: 'Brosse à dent Oral-B', p: 1.750, i: 'https://cdn.geantdrive.tn/tunis-city/1265885-home_default/brosse-a-dent.jpg', c: 'Hygiène' },
  { n: 'Lingettes antibactériennes', p: 1.750, i: 'https://cdn.geantdrive.tn/tunis-city/1203605-home_default/lingettes-antibacteriennes.jpg', c: 'Hygiène' },
  { n: 'Peigne à coupe', p: 1.790, i: 'https://cdn.geantdrive.tn/tunis-city/1247704-home_default/peigne-a-coupe.jpg', c: 'Hygiène' },
  { n: 'Savon de toilette Dove', p: 1.800, i: 'https://cdn.geantdrive.tn/tunis-city/966576-home_default/savon-de-toilette.jpg', c: 'Hygiène' },
  { n: 'Brosse à dents Philips', p: 1.850, i: 'https://cdn.geantdrive.tn/tunis-city/1325199-home_default/brosse-a-dents.jpg', c: 'Hygiène' },
  { n: 'Peigne à queue', p: 1.880, i: 'https://cdn.geantdrive.tn/tunis-city/1181421-home_default/peigne-a-queue.jpg', c: 'Hygiène' },
  { n: 'Crème déodorante Nivea', p: 1.890, i: 'https://cdn.geantdrive.tn/tunis-city/1264993-home_default/creme-deodorante.jpg', c: 'Hygiène' },
  { n: 'Crème à raser Gillette', p: 1.890, i: 'https://cdn.geantdrive.tn/tunis-city/1197281-home_default/creme-a-raser.jpg', c: 'Hygiène' },

  // ==================== UNIVERS BÉBÉ (43 produits) ====================
  { n: 'Lingettes bébé Lilas x72', p: 1.450, i: 'https://cdn.geantdrive.tn/tunis-city/1292637-home_default/lingettes-bebe.jpg', c: 'Bébé' },
  { n: 'Lingettes bébé Pampers x64', p: 1.490, i: 'https://cdn.geantdrive.tn/tunis-city/1194576-home_default/lingettes-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé coton blanc', p: 1.500, i: 'https://cdn.geantdrive.tn/tunis-city/1208868-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé rose', p: 1.500, i: 'https://cdn.geantdrive.tn/tunis-city/1210203-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé bleu', p: 1.500, i: 'https://cdn.geantdrive.tn/tunis-city/1208876-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Lingettes bébé Huggies x80', p: 1.750, i: 'https://cdn.geantdrive.tn/tunis-city/1186567-home_default/lingettes-bebe.jpg', c: 'Bébé' },
  { n: 'Lingettes bébé Dodie x100', p: 1.760, i: 'https://cdn.geantdrive.tn/tunis-city/1197752-home_default/lingettes-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes ajourées fillettes', p: 1.990, i: 'https://cdn.geantdrive.tn/tunis-city/1210378-home_default/chaussettes-ajourees-fillettes.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé motifs animaux', p: 1.990, i: 'https://cdn.geantdrive.tn/tunis-city/1210187-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé étoiles', p: 1.990, i: 'https://cdn.geantdrive.tn/tunis-city/1210188-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé cœurs', p: 1.990, i: 'https://cdn.geantdrive.tn/tunis-city/1210189-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Soquettes fille roses', p: 1.990, i: 'https://cdn.geantdrive.tn/tunis-city/1193802-home_default/soquettes-fille.jpg', c: 'Bébé' },
  { n: 'Soquettes fille blanches', p: 1.990, i: 'https://cdn.geantdrive.tn/tunis-city/1193806-home_default/soquettes-fille.jpg', c: 'Bébé' },
  { n: 'Lingettes de voyage bébé', p: 2.050, i: 'https://cdn.geantdrive.tn/tunis-city/1333687-home_default/lingettes-de-voyage-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé rayées bleues', p: 2.090, i: 'https://cdn.geantdrive.tn/tunis-city/1195588-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Chaussettes bébé rayées roses', p: 2.090, i: 'https://cdn.geantdrive.tn/tunis-city/1195569-home_default/chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Mini chaussettes bébé', p: 2.290, i: 'https://cdn.geantdrive.tn/tunis-city/1210387-home_default/mini-chaussettes-bebe.jpg', c: 'Bébé' },
  { n: 'Compote Blédina Pomme', p: 2.290, i: 'https://cdn.geantdrive.tn/tunis-city/1157913-home_default/compote.jpg', c: 'Bébé' },
  { n: 'Compote sans sucre ajouté', p: 2.290, i: 'https://cdn.geantdrive.tn/tunis-city/1162862-home_default/compote-sans-sucre-ajoute.jpg', c: 'Bébé' },
  { n: 'Compote mix fruits', p: 2.290, i: 'https://cdn.geantdrive.tn/tunis-city/1332316-home_default/compote.jpg', c: 'Bébé' },
  { n: 'Savon pour bébé Johnson', p: 2.410, i: 'https://cdn.geantdrive.tn/tunis-city/1247493-home_default/savon-pour-bebe.jpg', c: 'Bébé' },

  // ==================== PRODUITS MÉNAGERS (43 produits) ====================
  { n: 'Sac à bretelle', p: 0.220, i: 'https://cdn.geantdrive.tn/tunis-city/1203514-home_default/sac-a-bretelle.jpg', c: 'Entretien' },
  { n: 'Eponge Gratte-ciel x2', p: 0.590, i: 'https://cdn.geantdrive.tn/tunis-city/974290-home_default/eponge.jpg', c: 'Entretien' },
  { n: 'Chiffon microfibre', p: 0.630, i: 'https://cdn.geantdrive.tn/tunis-city/1249201-home_default/chiffon.jpg', c: 'Entretien' },
  { n: 'Chamoisine', p: 0.720, i: 'https://cdn.geantdrive.tn/tunis-city/1249145-home_default/chamoisine.jpg', c: 'Entretien' },
  { n: 'Savon de lavage OMO', p: 0.910, i: 'https://cdn.geantdrive.tn/tunis-city/1159371-home_default/savon-de-lavage.jpg', c: 'Entretien' },
  { n: 'Tampons à récurer verts', p: 0.950, i: 'https://cdn.geantdrive.tn/tunis-city/974293-home_default/tampons-a-recurer.jpg', c: 'Entretien' },
  { n: 'Savon de lavage Ariel', p: 0.980, i: 'https://cdn.geantdrive.tn/tunis-city/1159373-home_default/savon-de-lavage.jpg', c: 'Entretien' },
  { n: 'Savon de ménage Nadhif', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1331880-home_default/savon-de-menage.jpg', c: 'Entretien' },
  { n: 'Serpillère gaufrée', p: 1.070, i: 'https://cdn.geantdrive.tn/tunis-city/1247412-home_default/serpillere.jpg', c: 'Entretien' },
  { n: 'Pelle à poussière', p: 1.190, i: 'https://cdn.geantdrive.tn/tunis-city/974295-home_default/pelle-a-poussiere.jpg', c: 'Entretien' },
  { n: 'Serpillère coton', p: 1.250, i: 'https://cdn.geantdrive.tn/tunis-city/1245623-home_default/serpillere.jpg', c: 'Entretien' },
  { n: 'Eponge multi-usages', p: 1.290, i: 'https://cdn.geantdrive.tn/tunis-city/1075104-home_default/eponge.jpg', c: 'Entretien' },
  { n: 'Tampons à récurer jaunes', p: 1.290, i: 'https://cdn.geantdrive.tn/tunis-city/1247385-home_default/tampons-a-recurer.jpg', c: 'Entretien' },
  { n: 'Sac polypropylène réutilisable', p: 1.300, i: 'https://cdn.geantdrive.tn/tunis-city/1184034-home_default/sac-polypropylene-reutilisable.jpg', c: 'Entretien' },
  { n: 'Poudre mains Nadhif', p: 1.350, i: 'https://cdn.geantdrive.tn/tunis-city/1158151-home_default/poudre-mains.jpg', c: 'Entretien' },
  { n: 'Tampon éponge à récurer', p: 1.350, i: 'https://cdn.geantdrive.tn/tunis-city/974294-home_default/tampon-eponge-a-recurer.jpg', c: 'Entretien' },
  { n: 'Tampons abrasifs', p: 1.420, i: 'https://cdn.geantdrive.tn/tunis-city/1247381-home_default/tampons.jpg', c: 'Entretien' },
  { n: 'Savon de lavage Skip', p: 1.450, i: 'https://cdn.geantdrive.tn/tunis-city/1159375-home_default/savon-de-menage.jpg', c: 'Entretien' },
  { n: 'Lavette multi-usages', p: 1.500, i: 'https://cdn.geantdrive.tn/tunis-city/1247800-home_default/lavette-multi-usages.jpg', c: 'Entretien' },
  { n: 'Poudre mains Persil', p: 1.630, i: 'https://cdn.geantdrive.tn/tunis-city/1160958-home_default/poudre-mains.jpg', c: 'Entretien' },
  { n: 'Sacs poubelle 30L x10', p: 1.650, i: 'https://cdn.geantdrive.tn/tunis-city/1193944-home_default/sacs-poubelle.jpg', c: 'Entretien' },
  { n: 'Tampons éponge à récurer', p: 1.650, i: 'https://cdn.geantdrive.tn/tunis-city/1247700-home_default/tampons-eponge-a-recurer.jpg', c: 'Entretien' },
  { n: 'Tampon éponge à récurer anti-graffiti', p: 2.150, i: 'https://cdn.geantdrive.tn/tunis-city/1143980-home_default/tampon-eponge-a-recurer-anti-graffiti.jpg', c: 'Entretien' },

  // ==================== MAISON (38 produits) ====================
  { n: 'Entonnoir plastique petit', p: 0.790, i: 'https://cdn.geantdrive.tn/tunis-city/1152700-home_default/entonnoir.jpg', c: 'Maison' },
  { n: 'Sacs pour vêtements', p: 0.800, i: 'https://cdn.geantdrive.tn/tunis-city/1178927-home_default/sacs-pour-vetements.jpg', c: 'Maison' },
  { n: 'Entonnoir plastique moyen', p: 0.990, i: 'https://cdn.geantdrive.tn/tunis-city/1152703-home_default/entonnoir.jpg', c: 'Maison' },
  { n: 'Gobelet incassable', p: 1.020, i: 'https://cdn.geantdrive.tn/tunis-city/1150669-home_default/gobelet-incassable.jpg', c: 'Maison' },
  { n: 'Plat oval', p: 1.190, i: 'https://cdn.geantdrive.tn/tunis-city/896280-home_default/plat-oval.jpg', c: 'Maison' },
  { n: 'Gobelet granity', p: 1.220, i: 'https://cdn.geantdrive.tn/tunis-city/1161261-home_default/gobelet-granity.jpg', c: 'Maison' },
  { n: 'Entonnoir plastique grand', p: 1.450, i: 'https://cdn.geantdrive.tn/tunis-city/1152705-home_default/entonnoir.jpg', c: 'Maison' },
  { n: 'Mini plat', p: 1.490, i: 'https://cdn.geantdrive.tn/tunis-city/1269296-home_default/mini-plat.jpg', c: 'Maison' },
  { n: 'Congemix petit', p: 1.490, i: 'https://cdn.geantdrive.tn/tunis-city/1282698-home_default/congemix.jpg', c: 'Maison' },
  { n: 'Couteaux plastique', p: 1.500, i: 'https://cdn.geantdrive.tn/tunis-city/1210689-home_default/couteaux.jpg', c: 'Maison' },
  { n: 'Salière poivrier', p: 1.500, i: 'https://cdn.geantdrive.tn/tunis-city/1179255-home_default/saliere-poivrier.jpg', c: 'Maison' },
  { n: 'Pinces à linge bois', p: 1.600, i: 'https://cdn.geantdrive.tn/tunis-city/1349862-home_default/pinces-a-linge.jpg', c: 'Maison' },
  { n: 'Boîte de conservation', p: 1.690, i: 'https://cdn.geantdrive.tn/tunis-city/853634-home_default/boite-de-conservation.jpg', c: 'Maison' },
  { n: 'Pot de conservation', p: 1.750, i: 'https://cdn.geantdrive.tn/tunis-city/1308448-home_default/pot-de-conservation.jpg', c: 'Maison' },
  { n: 'Gourde enfant', p: 1.790, i: 'https://cdn.geantdrive.tn/tunis-city/876759-home_default/gourde-enfant.jpg', c: 'Maison' },
  { n: 'Accroche-tout', p: 1.790, i: 'https://cdn.geantdrive.tn/tunis-city/1269231-home_default/accroche-tout.jpg', c: 'Maison' },
  { n: 'Pinces à linge plastique', p: 1.800, i: 'https://cdn.geantdrive.tn/tunis-city/1349863-home_default/pinces-a-linge.jpg', c: 'Maison' },
  { n: 'Boîte à repas carry lunch box', p: 1.890, i: 'https://cdn.geantdrive.tn/tunis-city/1270999-home_default/boite-a-repas-carry-lunch-box.jpg', c: 'Maison' },
  { n: 'Mug céramique', p: 1.890, i: 'https://cdn.geantdrive.tn/tunis-city/1349878-home_default/mug.jpg', c: 'Maison' },
  { n: 'Pailles normales', p: 1.940, i: 'https://cdn.geantdrive.tn/tunis-city/1309111-home_default/pailles-normales.jpg', c: 'Maison' },
  { n: 'Fourchettes plastique', p: 1.950, i: 'https://cdn.geantdrive.tn/tunis-city/1269297-home_default/fourchettes.jpg', c: 'Maison' },
  { n: 'Cuillères plastique', p: 1.950, i: 'https://cdn.geantdrive.tn/tunis-city/1269299-home_default/cuilleres.jpg', c: 'Maison' },
  { n: 'Boîte de conservation rectangulaire', p: 2.190, i: 'https://cdn.geantdrive.tn/tunis-city/1076292-home_default/boite-de-conservation-rectangulaire.jpg', c: 'Maison' },
  { n: 'Sous verre', p: 2.190, i: 'https://cdn.geantdrive.tn/tunis-city/1321992-home_default/sous-verre.jpg', c: 'Maison' },
  { n: 'Assiettes plastique', p: 2.300, i: 'https://cdn.geantdrive.tn/tunis-city/1152964-home_default/assiettes.jpg', c: 'Maison' },
];

const generateProducts = (): Product[] => {
  return RAW_DATA.map((item, index) => ({
    id: `p-geant-${index + 1}`,
    barcode: `619${Math.floor(1000000000 + Math.random() * 9000000000)}`,
    name: item.n,
    category: item.c,
    buyPrice: parseFloat((item.p * 0.85).toFixed(3)), // Marge de 15%
    sellPrice: item.p,
    tva: 19,
    stockQuantity: 20 + Math.floor(Math.random() * 80),
    minStock: 5,
    imageUrl: item.i
  }));
};

export const MOCK_PRODUCTS: Product[] = generateProducts();

// Update MOCK_CUSTOMERS to include loyaltyPoints
export const MOCK_CUSTOMERS: Customer[] = [
  { id: 'c1', name: 'Mohamed Ben Salah', phone: '22333444', creditBalance: 45.500, loyaltyPoints: 0 },
  { id: 'c2', name: 'Sami Ben Salem', phone: '98765432', creditBalance: 0, loyaltyPoints: 0 },
  { id: 'c3', name: 'Moufida Trabelsi', phone: '55666777', creditBalance: 12.300, loyaltyPoints: 0 },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  { id: 's1', name: 'SFBT Tunisie', contact: '71000111', debt: 1200.000 },
  { id: 's2', name: 'Délice Tunisie', contact: '71222333', debt: 450.000 },
  { id: 's3', name: 'Géant Drive B2B', contact: '72444555', debt: 0 },
];

export const APP_USERS: User[] = [
  { id: 'u1', name: 'Admin (Géant City)', role: 'ADMIN' },
  { id: 'u2', name: 'Caissier (Zied)', role: 'CASHIER' },
];
